#!/usr/bin/env python3
"""Checks Doxygen coverage for project headers and critical runtime sources."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import sys


RE_CLASS_OR_STRUCT = re.compile(r"^\s*(class|struct)\s+([A-Za-z_][A-Za-z0-9_]*)\b")
RE_ACCESS_SPECIFIER = re.compile(r"^\s*(public|private|protected)\s*:\s*$")

SKIP_FUNCTION_PREFIXES = (
    "using ",
    "typedef ",
    "friend ",
    "if ",
    "for ",
    "while ",
    "switch ",
    "return ",
    "static_assert",
    "#",
)

FUNCTION_PREFIX_QUALIFIERS = {
    "virtual",
    "inline",
    "constexpr",
    "consteval",
    "constinit",
    "static",
    "explicit",
    "extern",
}


@dataclass(frozen=True)
class Issue:
    file: str
    line: int
    symbol: str
    missing_tags: tuple[str, ...]


@dataclass
class ScopeState:
    name: str
    access: str
    depth: int


HEADER_SCAN_DIRS = (
    "core/include",
    "server/include",
    "gateway/include",
    "client_gui/include",
)

HEADER_SUFFIXES = {".hpp", ".h", ".hh"}

CRITICAL_CPP_FILES = (
    "server/src/app/bootstrap.cpp",
    "server/src/app/router.cpp",
    "server/src/app/core_internal_adapter.cpp",
    "server/src/app/metrics_server.cpp",
    "gateway/src/gateway_app.cpp",
    "tools/wb_worker/main.cpp",
)


def is_generated_header(path: Path) -> bool:
    try:
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:12])
    except OSError:
        return False
    return (
        "자동 생성 파일" in head
        or "Generated by" in head
        or "generated by" in head
    )


def find_preceding_doxygen_block(lines: list[str], decl_line_index: int) -> str | None:
    i = decl_line_index - 1
    while i >= 0 and (
        lines[i].strip() == ""
        or lines[i].lstrip().startswith("template<")
        or lines[i].lstrip().startswith("template <")
    ):
        i -= 1

    if i < 0:
        return None

    current = lines[i].lstrip()
    if current.startswith("///"):
        start = i
        while start - 1 >= 0 and lines[start - 1].lstrip().startswith("///"):
            start -= 1
        return "\n".join(lines[start : i + 1])

    if lines[i].rstrip().endswith("*/"):
        start = i
        while start >= 0:
            row = lines[start]
            if "/**" in row:
                return "\n".join(lines[start : i + 1])
            if "/*" in row and "/**" not in row:
                return None
            start -= 1

    return None


def check_header_file(path: Path, root: Path) -> list[Issue]:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    rel = path.relative_to(root).as_posix()
    issues: list[Issue] = []

    class_stack: list[ScopeState] = []
    brace_depth = 0

    for idx, line in enumerate(lines):
        stripped = line.strip()

        if class_stack:
            access_match = RE_ACCESS_SPECIFIER.match(line)
            if access_match:
                class_stack[-1].access = access_match.group(1)

        m = RE_CLASS_OR_STRUCT.match(line)
        if not m:
            pass
        else:
            symbol = m.group(2)
            kind = m.group(1)
            stripped_decl = line.strip()

            # Skip forward declarations.
            if not (stripped_decl.endswith(";") and "{" not in stripped_decl):
                block = find_preceding_doxygen_block(lines, idx)
                missing: list[str] = []
                if block is None or "@brief" not in block:
                    missing.append("@brief")

                if missing:
                    issues.append(
                        Issue(
                            file=rel,
                            line=idx + 1,
                            symbol=symbol,
                            missing_tags=tuple(missing),
                        )
                    )

                if "{" in line:
                    delta = line.count("{") - line.count("}")
                    scope_depth = brace_depth + delta
                    default_access = "private" if kind == "class" else "public"
                    class_stack.append(ScopeState(name=symbol, access=default_access, depth=scope_depth))

        if _is_function_declaration_candidate(stripped):
            scope = class_stack[-1] if class_stack else None

            # Class member declarations are valid only at the direct class body depth.
            if scope and brace_depth != scope.depth:
                pass
            elif scope and scope.access != "public":
                pass
            else:
                block = find_preceding_doxygen_block(lines, idx)
                if block is not None:
                    missing = _missing_function_tags(stripped, block, scope.name if scope else None)
                    if missing:
                        symbol = _extract_decl_symbol(stripped)
                        issues.append(
                            Issue(
                                file=rel,
                                line=idx + 1,
                                symbol=symbol,
                                missing_tags=tuple(missing),
                            )
                        )

        brace_depth += line.count("{") - line.count("}")
        while class_stack and brace_depth < class_stack[-1].depth:
            class_stack.pop()

    return issues


def _is_function_declaration_candidate(stripped: str) -> bool:
    if not stripped:
        return False
    if not stripped.endswith(";"):
        return False
    if "(" not in stripped or ")" not in stripped:
        return False
    if "{" in stripped or "}" in stripped:
        return False
    if any(stripped.startswith(prefix) for prefix in SKIP_FUNCTION_PREFIXES):
        return False
    return True


def _extract_decl_symbol(stripped: str) -> str:
    prefix = stripped.split("(", 1)[0].strip()
    if not prefix:
        return "(function)"
    token = prefix.split()[-1]
    return token.split("::")[-1]


def _missing_function_tags(stripped: str, block: str, class_name: str | None) -> list[str]:
    prefix = stripped.split("(", 1)[0].strip()
    params_text = stripped[stripped.find("(") + 1 : stripped.rfind(")")].strip()

    # Extract function name and return token candidates.
    raw_tokens = prefix.replace("&", " ").replace("*", " ").split()
    tokens = [t for t in raw_tokens if t not in FUNCTION_PREFIX_QUALIFIERS]
    if not tokens:
        return []

    name = tokens[-1].split("::")[-1]
    ret_tokens = tokens[:-1]

    is_ctor_or_dtor = False
    if class_name and (name == class_name or name == f"~{class_name}"):
        is_ctor_or_dtor = True

    needs_param = params_text not in ("", "void")

    needs_return = False
    if not is_ctor_or_dtor:
        if ret_tokens:
            needs_return = ret_tokens[-1] != "void"

    missing: list[str] = []
    if needs_param and "@param" not in block:
        missing.append("@param")
    if needs_return and "@return" not in block:
        missing.append("@return")
    return missing


def collect_header_issues(root: Path) -> list[Issue]:
    issues: list[Issue] = []

    for scan_dir in HEADER_SCAN_DIRS:
        base = root / scan_dir
        if not base.exists():
            continue

        for path in base.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in HEADER_SUFFIXES:
                continue
            if is_generated_header(path):
                continue
            issues.extend(check_header_file(path, root))

    return issues


def collect_critical_cpp_issues(root: Path) -> list[Issue]:
    issues: list[Issue] = []
    for rel in CRITICAL_CPP_FILES:
        path = root / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if "@brief" in text:
            continue
        issues.append(
            Issue(
                file=rel,
                line=1,
                symbol="(file)",
                missing_tags=("@brief",),
            )
        )
    return issues


def print_report(issues: list[Issue]) -> None:
    print(f"[doxygen] FAILED: {len(issues)} issue(s)")
    print("[doxygen] format: file:line | symbol | missing_tags")
    for issue in issues:
        tags = ", ".join(issue.missing_tags)
        print(f"- {issue.file}:{issue.line} | {issue.symbol} | {tags}")


def main() -> int:
    root = Path(__file__).resolve().parents[1]

    issues = collect_header_issues(root)
    issues.extend(collect_critical_cpp_issues(root))
    issues = sorted(issues, key=lambda x: (x.file, x.line, x.symbol))

    if issues:
        print_report(issues)
        return 1

    print("[doxygen] PASS: coverage checks succeeded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
